version: '2.1'
services:
  api:
    build: ./api
    ports:
    - "8080:8080"
    depends_on:
    - "redis"
    - "liquibase"
  processor:
    build: ./processor
    depends_on:
    - "redis"
    - "liquibase"
  redis:
    image: redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: adventureworks
      MYSQL_USER: advuser
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysql"]
  liquibase:
    image: changelog-image
    depends_on:
      db:
        condition: service_healthy
    links:
    - "db"
    command: liquibase --logLevel=debug update